version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'thursday'
    versioning-strategy: increase
    commit-message:
      prefix: 'feat(metadata)'
    allow:
      - dependency-name: '@salesforce/source-deploy-retrieve'
      - dependency-name: 'config-disassembler'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    commit-message:
      prefix: "build"
