APPLY_FIXES: none
VALIDATE_ALL_CODEBASE: false

# cspell:disable
FILTER_REGEX_EXCLUDE: (\.git|node_modules|lib|coverage|fixtures|\.eslintcache)

ENABLE_LINTERS:
  - JAVASCRIPT_ES
  - TYPESCRIPT_ES
  - MARKDOWN_MARKDOWNLINT
  - SPELL_CSPELL

# Reuse existing ESLint config
JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.cjs
TYPESCRIPT_ES_CONFIG_FILE: .eslintrc.cjs

SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
