blank_issues_enabled: true
contact_links:
  - name: Discussions
    url: https://github.com/mcarvin8/sf-decomposer/discussions
    about: Open-ended questions, recipes, or "is this supported?" go here.
