name: Test

on:
  push:
    branches-ignore:
      - main

jobs:
  unit-tests:
    uses: salesforcecli/github-workflows/.github/workflows/unitTest.yml@main
  nuts:
    needs: unit-tests
    uses: salesforcecli/github-workflows/.github/workflows/nut.yml@main
    secrets: inherit
    strategy:
      matrix:
        os: [windows-latest]
      fail-fast: false
    with:
      os: ${{ matrix.os }}
